# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='store.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0bstore.proto\"A\n\nGetMessage\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x13\n\x0b\x63onsistency\x18\x02 \x01(\r\x12\x11\n\ttimestamp\x18\x03 \x01(\r\"P\n\nPutMessage\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\t\x12\x13\n\x0b\x63onsistency\x18\x03 \x01(\r\x12\x11\n\ttimestamp\x18\x04 \x01(\r\";\n\rCoordToClient\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x08\"\x94\x01\n\x0eRequestMessage\x12\"\n\x0bget_message\x18\x01 \x01(\x0b\x32\x0b.GetMessageH\x00\x12\"\n\x0bput_message\x18\x02 \x01(\x0b\x32\x0b.PutMessageH\x00\x12\'\n\rcoord_message\x18\x03 \x01(\x0b\x32\x0e.CoordToClientH\x00\x42\x11\n\x0frequest_messageb\x06proto3')
)




_GETMESSAGE = _descriptor.Descriptor(
  name='GetMessage',
  full_name='GetMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='GetMessage.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='consistency', full_name='GetMessage.consistency', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='GetMessage.timestamp', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=80,
)


_PUTMESSAGE = _descriptor.Descriptor(
  name='PutMessage',
  full_name='PutMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='PutMessage.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='PutMessage.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='consistency', full_name='PutMessage.consistency', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='PutMessage.timestamp', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=162,
)


_COORDTOCLIENT = _descriptor.Descriptor(
  name='CoordToClient',
  full_name='CoordToClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='CoordToClient.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='CoordToClient.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='CoordToClient.status', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=223,
)


_REQUESTMESSAGE = _descriptor.Descriptor(
  name='RequestMessage',
  full_name='RequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='get_message', full_name='RequestMessage.get_message', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='put_message', full_name='RequestMessage.put_message', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coord_message', full_name='RequestMessage.coord_message', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='request_message', full_name='RequestMessage.request_message',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=226,
  serialized_end=374,
)

_REQUESTMESSAGE.fields_by_name['get_message'].message_type = _GETMESSAGE
_REQUESTMESSAGE.fields_by_name['put_message'].message_type = _PUTMESSAGE
_REQUESTMESSAGE.fields_by_name['coord_message'].message_type = _COORDTOCLIENT
_REQUESTMESSAGE.oneofs_by_name['request_message'].fields.append(
  _REQUESTMESSAGE.fields_by_name['get_message'])
_REQUESTMESSAGE.fields_by_name['get_message'].containing_oneof = _REQUESTMESSAGE.oneofs_by_name['request_message']
_REQUESTMESSAGE.oneofs_by_name['request_message'].fields.append(
  _REQUESTMESSAGE.fields_by_name['put_message'])
_REQUESTMESSAGE.fields_by_name['put_message'].containing_oneof = _REQUESTMESSAGE.oneofs_by_name['request_message']
_REQUESTMESSAGE.oneofs_by_name['request_message'].fields.append(
  _REQUESTMESSAGE.fields_by_name['coord_message'])
_REQUESTMESSAGE.fields_by_name['coord_message'].containing_oneof = _REQUESTMESSAGE.oneofs_by_name['request_message']
DESCRIPTOR.message_types_by_name['GetMessage'] = _GETMESSAGE
DESCRIPTOR.message_types_by_name['PutMessage'] = _PUTMESSAGE
DESCRIPTOR.message_types_by_name['CoordToClient'] = _COORDTOCLIENT
DESCRIPTOR.message_types_by_name['RequestMessage'] = _REQUESTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetMessage = _reflection.GeneratedProtocolMessageType('GetMessage', (_message.Message,), dict(
  DESCRIPTOR = _GETMESSAGE,
  __module__ = 'store_pb2'
  # @@protoc_insertion_point(class_scope:GetMessage)
  ))
_sym_db.RegisterMessage(GetMessage)

PutMessage = _reflection.GeneratedProtocolMessageType('PutMessage', (_message.Message,), dict(
  DESCRIPTOR = _PUTMESSAGE,
  __module__ = 'store_pb2'
  # @@protoc_insertion_point(class_scope:PutMessage)
  ))
_sym_db.RegisterMessage(PutMessage)

CoordToClient = _reflection.GeneratedProtocolMessageType('CoordToClient', (_message.Message,), dict(
  DESCRIPTOR = _COORDTOCLIENT,
  __module__ = 'store_pb2'
  # @@protoc_insertion_point(class_scope:CoordToClient)
  ))
_sym_db.RegisterMessage(CoordToClient)

RequestMessage = _reflection.GeneratedProtocolMessageType('RequestMessage', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTMESSAGE,
  __module__ = 'store_pb2'
  # @@protoc_insertion_point(class_scope:RequestMessage)
  ))
_sym_db.RegisterMessage(RequestMessage)


# @@protoc_insertion_point(module_scope)
